### ISSUE TITLE
[Firefox] Not working with multiple windows open

### ISSUE THREAD

**Issue by albemala** [protestContest/whatfont-webextension#1]
Hi!

First of all, thank you for porting this extension to Firefox, it's very useful!

I noticed when I have more than one window open and I activate the extension, it will show up in a random window, not necessarily the one I activated it from. Would it be possible to fix this? Thank you!

Tested on macOS, Firefox 65

**Comment by protestContest** [comment]
Fixed! Should be updated on addons.mozilla.org shortly. Thanks for spotting that!

**Comment by albemala** [comment]
Awesome, thank you so much!
